name: Daily Commit Workflow

on:
  schedule:
    - cron: '*/5 * * * * echo "Hello" >/dev/null 2>&1'  # Daily at 04:30 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add timestamp file for 23f3000663@ds.study.iitm.ac.in
        run: |
          echo "Updated at: $(date -u +'%Y-%m-%dT%H:%M:%SZ')" > .daily_update.txt
          git config --global user.name "github-actions"
          git config --global user.email "23f3000663@ds.study.iitm.ac.in"
          git add .daily_update.txt
          git commit -m "Automated daily update"
          git push
