name: Scrape IMDb Top 250

on:
  schedule:
    - cron: '30 3 * * *'  # Runs daily at 03:30 UTC
  workflow_dispatch:

jobs:
  scrape-imdb:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Run scraper (by 23f3000663@ds.study.iitm.ac.in)
        run: |
          uv run --with httpx,lxml,cssselect python scrape.py

      - name: Commit scraped data
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "23f3000663@ds.study.iitm.ac.in"
          git add *.json
          git commit -m "Daily scrape and commit by 23f3000663@ds.study.iitm.ac.in" || echo "No changes"
          git push
